Exercise Two css grid
AndresR9707/css-tutorial pull request #8
Opened 2021-01-28 05:02 UTC by AndresR9707

2021-01-28 21:56 UTC, pushdev-code requested changes

2021-01-28 21:56 UTC, pushdev-code commented on 4-css-grid/exercise.html
> +            <div class="box header">
use semantic tags.
```suggestion
            <header class="box header">
```

2021-01-28 21:56 UTC, pushdev-code commented on 4-css-grid/exercise.html
> +            <div class="box leftS">
```suggestion
            <aside class="box leftS">
```

2021-01-28 21:56 UTC, pushdev-code commented on 4-css-grid/exercise.html
> +            </div>
```suggestion
            <section class="box article">
                <article>Article</article>
            </section>
```

2021-01-28 21:56 UTC, pushdev-code commented on 4-css-grid/exercise.html
> +            <div class="box rightS">
```suggestion
            <aside class="box rightS">
```

2021-01-28 21:56 UTC, pushdev-code commented on 4-css-grid/exercise.html
> +            <div class="box footer">
```suggestion
            <footer class="box footer">
```

2021-01-28 21:56 UTC, pushdev-code commented on 4-css-grid/styles.css
> +    grid-gap: 1em;
Sort CSS properties from A-Z

2021-02-02 11:05 UTC, fabianmarinog requested changes

2021-02-02 11:05 UTC, fabianmarinog commented on 4-css-grid/exercise.html
> +            </div>
```suggestion
            </header>
```

2021-02-02 11:05 UTC, fabianmarinog commented on 4-css-grid/exercise.html
> +            </div>
```suggestion
            </aside>
```

2021-02-02 11:05 UTC, fabianmarinog commented on 4-css-grid/exercise.html
> +            </div>
```suggestion
            </aside>
```

2021-02-02 11:05 UTC, fabianmarinog commented on 4-css-grid/exercise.html
> +            </div>
```suggestion
            </footer>
```

2021-02-03 10:59 UTC, merged